### ISSUE TITLE
App is incorrectly reported as outdated if it takes too long to load

### ISSUE THREAD

**Issue by matthewhilton** [Shopify/shopify-app-bridge#160]
## Describe the bug

If an app takes too long to load, it will be incorrectly reported as being outdated when using an admin.shopify.com domain (aka unified admin)

I have checked my app configuration (app bridge, frame ancestors headers, etc...) and all is following the guidelines.

The error originally showed occasionally when the app loaded for the first time in a new browser, which makes sense as the load time will be slightly longer due to caching js, css, etc. This would happen about 1 in 10 loads.

If I introduce an artificial sleep of for e.g. 5 seconds in my app loading route, the error shows up 100% the time.

![image](https://user-images.githubusercontent.com/17095477/200721238-6e5a6776-dedc-482f-9e28-f816ed996592.png)

### To Reproduce

Steps to reproduce the behaviour:

Prerequisites:
1. Be on the new unified admin domain e.g. `admin.shopify.com/stores/xyz`
2. Introduce an artificial sleep of 5 seconds in the app load script to simulate a slow network connection / fresh load of app

Reproduce:
1. Launch app
3. Error is shown

### Expected behaviour

I am guessing it is checking for the existence of the AppBridgeProvider, albeit slightly too early. However since App bridge is closed source this is just a guess.

I would expect that the Admin UI waits until the app is completely loaded before checking for its existence.

### Packages and versions

- "@shopify/app": "^3.22.1",
- "@shopify/app-bridge-react": "^3.4.3",
- "@shopify/app-bridge-utils": "^3.4.3",
- "@shopify/cli": "^3.22.1",
- "@shopify/polaris": "^9.19.0",
- "@shopify/polaris-icons": "^4.23.0",
- "@shopify/shopify-api": "^5.2.0",

## Platform

- Browser: Firefox 106.0.5 (64-bit)

**Comment by mbaumbach** [comment]
This message is confusing merchants and partners alike. Partners aren't sure how to fix this (or if it's a bug) and merchants are concerned that apps are no longer going to function. We've only had a couple merchants bring it up, but we can't reproduce it without introducing the 5 second timeout mentioned in the description.

I feel like this message should be presented to partners in the partner portal if there's an issue (similar to the API deprecations) and it should be documented what needs to be addressed to no longer be outdated. Presenting this to merchants only, especially with deprecation nearly a year out, seems like it is causing unnecessary concern for everybody.

If this isn't a bug, I imagine the five second limit is also a bit tight for some partners. Especially on a first load with uncached resources. It’s also greatly dependent on the network connection of the merchant. If a single merchant crosses this threshold does that mean the app is no longer up to date and could be removed for all merchants? Is there a more deterministic measure of app performance that could be implemented here?

**Comment by aw-katusev** [comment]
This is definitely something merchants shouldn't see. But partners need to have it in the Apps -> app details page so they know what to do. Shopify usually sends notifications in partenr panel, via email or marks as a mandatory api update. This case is not an exception. 

Also, we successfully passed app audit and introduced necessary fixes where it was necessary less than two months ago. So we were confident that everything is fine from technical perspective.

**Comment by matthewhilton** [comment]
I should make it clear the 5 seconds example I gave is arbitrary - I do not know the actual time it is testing or if it is even checking after X number of seconds at all. It could actually just be a coincidence that this check happens after loading xyz script that just so happens to take X seconds to load.

I am using serverless functions to load my app, and so this happens every time there is a cold start which means usually ~ 5-6 seconds but after that every load is < 2 seconds.

While I can workaround the issue by hyper optimising and pre-warming my serverless functions - the root cause of this problem is that this check should actually just wait for the script to actually return some HTML or wait for the DOM to settle.

There's also the problem that as partners we cannot create test stores using the new unified admin `admin.shopify.com` - the only reason I discovered this bug was because the app reviewer (who do have access to the unified admin) ran into the bug and allowed me collaborator access.

**Comment by matthewhilton** [comment]
I have done the following to try and debug this issue:

1. Test pre-warming serverless functions. - This did not work, I have watched a 500ms load of the app/load function be shown this error
2. Test a smaller bundle size. My app loads a serverless function before redirecting to the HTML / React JS bundle. Since my App uses NextJS and has a non trivially sized JS bundle, I was thinking maybe the downloading of the bundle was too slow. So I tried making it return instead a plain HTML page with only the minimum JS to initiate an app bridge connection. - This did not work either.

The only way I can consistently reproduce it is to force an unnecessarily large loading time (e.g. 5 seconds), however, this should mean that fast loads (e.g. 500ms) _shouldn't_ be shown this error, but this is not the case.

This leads me to believe it could be a combination of my apps loading time + the shopify admin loading time. I will keep doing some more tests.

**Comment by mbaumbach** [comment]
> In the short term, we’re going to increase the timeout for some extra margin of safety, however, it’s already quite a long period for a user to wait for an app load. A bit longer term, we’re working on an update to this logic that does not rely on this timer, and looks at the app’s past behavior to determine if an app is compatible with the upcoming changes, and whether to show the banner.

Thanks for the update @AaronSpringut, that change sounds encouraging!

**Comment by cyberabis** [comment]
> Hey folks. This alert is part of the warning for our [upcoming changes to the url structure](https://www.shopify.com/partners/blog/september-product-updates-for-partners-and-developers). At the moment, only merchants in the beta programs for these changes will see the banner. Part of the current detection for apps that do not follow the guidance is a timeout period. If an app does not initialize an up to date version of App Bridge before the timeout, the Shopify admin assumes the app is not compatible with the upcoming changes and a warning is shown to direct the user to the myshopify domain.
> 
> In the short term, we’re going to increase the timeout for some extra margin of safety, however, it’s already quite a long period for a user to wait for an app load. A bit longer term, we’re working on an update to this logic that does not rely on this timer, and looks at the app’s past behavior to determine if an app is compatible with the upcoming changes, and whether to show the banner.

Hi @AaronSpringut , would like to bring a scenario to your notice. With multiple apps we are seeing the alert when the user signs up for the first time (when there is no user session in the Redis). The alert does not appear on subsequent app visits. So, I am guessing the very first app access with no session takes more time and hence the alert is showing up. It would be a very bad experience for a newly signing up customer to see this alert. We have made all other changes (App bridge 3, CSP Header, Host name etc.) and tested this even with light weight apps. Kind of in a dead-end on solving this. I'll be happy to share more details of our app if you need.

**Comment by traianturcu** [comment]
Is there a way to migrate one of our dev stores to use the new URL (admin.shopify.com/store/..) so we can test this specific issue for our apps?

**Comment by sandeepgit14** [comment]
@AaronSpringut we are facing the same popup always on one Shopify store and as per the Shopify guidelines, the app bridge is updated to the latest and the host parameter is also working. The Content-Security-Policy headers are also verified and there is no issue.

The app build is also upgraded and it's loading in less than 1 second but still, the issue is the same so it's not an issue with a timeout. I am not able to find any specific reason for the above popup issue.

The same code is working fine on the staging app and there is no such issue.

Any suggestions are most welcome!

**Comment by AaronSpringut** [comment]
@juona 
> @AaronSpringut
> 
> > If an app does not initialize an up to date version of App Bridge before the timeout, the Shopify admin assumes the app is not compatible with the upcoming changes and a warning is shown to direct the user to the myshopify domain.
> 
> Well, what if my app does not use App Bridge? :/ I still expect it to be launched from within Shopify via an iframe. That's what the app reviewer is attempting to do as well, as part of the review process. Unfortunately, it fails to load when launched from within this new unified admin, even though I have the correct CSP headers set (same error as the OP). Is this an oversight? Or are all new apps expected to use App Bridge?

Using App Bridge is a [requirement](https://shopify.dev/apps/store/requirements#a-embedding-into-the-shopify-admin) for App Store apps that are embedded in the Shopify Admin.

**Comment by lukasz-pw** [comment]
@AaronSpringut I agree with one of the comments that the popup message is misleading. It can affect trust in our app even though it may be a problem with the client's network speed, and not our app specifically. I think it's fair to make a loadtime a requirement for an app, and should be monitored and communicated to app owner, but it's not entirely fair to show a popup suggesting that the app is outdated and will no longer function.  

I realize that this affects only users using the new admin access URL, but this should be escalated as it may affect our business.

**Comment by psppro26** [comment]
@AaronSpringut I'm totally agree with others. My app is totally is up to date with the last requirements and i got some merchants reaching me ( even some asking for a full refund ) cause my app will be "outdated" and is no longer maintened.
I dont see the point to display this message to merchants ? why dont just send the alerts trough partner dashboard like API ones ?
Of course it's only affect users using the new admin access URL.
Thanks

**Comment by matthewhilton** [comment]
@Keemtaker The only way to really reduce this is to make your app load as fast as possible. I am using NextJs so it takes a while to download and cache the JS bundle, so what I did to mitigate this was to load a very simple HTML page with a JS script that just loads the app bridge, which would then redirect to the main app. I have since removed this though, as I think the increased timeout that was implemented has "fixed" this issue.

I highly suspect it is also at least partially dependent on the speed at which the shopify admin itself loads - which is out of your control.

Also just an FYI, if you email partner support they change a flag on the backend so that one of your dev stores can use the new unified admin domain so you can test this yourself.

**Comment by derrickrc** [comment]
In my testing, the workaround to this is to initialize `createApp` with the `host` parameter as soon as possible on the client side (even before authenticating the user, if needed) - you have about 5-6 seconds to do so after the user initially arrives at your app. This should prevent the message from showing, and whether or not you have CSP headers doesn't affect this message coming up based on my testing.

**Comment by assaflei** [comment]
Hi,
The recommendations provided here reference the app bridge javascript API
Is there a best practice recommendation for using the react component of app bridge ([details](https://shopify.dev/apps/tools/app-bridge/getting-started/using-react))?
My app bridge is initialized as part of the app render (the config object contains the host parameter)
```
<Provider config={config}>
    <AppProvider i18n={translations}>
        <Component {...pageProps} />
    </AppProvider>
</Provider>
```
I don't see how this can be separated from the rest of the app since its the app itself (I use nextjs to bundle everything)

**Comment by mingfengwan** [comment]
@AaronSpringut My app is literally built from a Shopify app template with every single library up to date, and this message still shows up. Developers should at least expect the app template provided by Shopify to be "error-free" instead of wrapping their heads around this.

**Comment by assaflei** [comment]
> > Hi, The recommendations provided here reference the app bridge javascript API Is there a best practice recommendation for using the react component of app bridge ([details](https://shopify.dev/apps/tools/app-bridge/getting-started/using-react))? My app bridge is initialized as part of the app render (the config object contains the host parameter)
> > ```
> > <Provider config={config}>
> >     <AppProvider i18n={translations}>
> >         <Component {...pageProps} />
> >     </AppProvider>
> > </Provider>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't see how this can be separated from the rest of the app since its the app itself (I use nextjs to bundle everything)
> 
> @assaflei I haven't used App Bridge react, but like you said it looks like the `Provider` config object is equivalent to the JS `createApp` method. I think as long as you return `Provider` within the first 5 seconds of the request, it should prevent the message from showing.

@derrickrc you suggest that I add a short js file executing the create app and follow on it with the rest of the nextjs app?

**Comment by patrickbolle** [comment]
Also seeing this on my app that is fully updated with no API version complaints. Merchants are getting incredibly confused. This is an awful message to show to end users.

**Comment by andrewle** [comment]
Facing this issue as well across multiple merchants. We're doing all the right things already regarding API versions, host parameter, and app bridge version as well as page speed. We're afraid merchants are uninstalling our app due to this message

**Comment by forsbergplustwo** [comment]
We're getting reports of this as well on our apps since this weekend. Running on AppBridge 3.0, CSP updated and app is faster than 5 secs to load. Not communicating all this to partners and instead showing a message about something changing in 9 months is kind of the opposite of a professional rollout. It's a major change affecting app developers and their customer's experience, with incorrect text and triggering.

Would be great if this could be looked into with priority please @AaronSpringut 😊

**Comment by cleverlight** [comment]
@AaronSpringut I'd also like to question the logic that says when an app is non-compliant or too slow, we should tell a storeowner that it needs updating: a storeowner who has no possible way to update it.  It's not only disempowering for them, it's scary because they feel like something bad is about to happen (albeit in 9 months) and the only person who can do something about it is someone they don't know!

Perhaps instead we could have an "app test" page in the Partner dashboard, that applies the current set of requirements to the app, measures its performance and highlights any shortfalls directly to the partner, who **can** then do something about it.

**Comment by AaronSpringut** [comment]
Thanks again for bringing this to our attention. To support Shopify admin’s 
migration to a new unified domain—admin.shopify.com—embedded apps were required to make updates, such as moving to App Bridge 3.0, to ensure the best merchant experience. Both the standard version of App Bridge and the React version (using the Provider component) will fulfill this requirement. The best practice is to initialize App Bridge as soon as possible when loading your site.

For apps that have not yet made these required updates, a blocking error message will be presented upon app load. However, this error message was erroneously presented for apps that had already been updated but were loading slowly. We apologize to all partners impacted by this. 

We’re working on a resolution that will provide clearer error messaging, and prevent it from being shown erroneously for apps that have made the required updates. You will continue to receive updates via email and through the partner dashboard.

Note: To ensure your app does not experience issues as the migration continues, if you have not already, please implement the required updates detailed [here](https://shopify.dev/apps/tools/app-bridge/updating-overview#ensure-compatibility-with-the-new-shopify-admin-domain).

**Comment by janklimo** [comment]
<img width="841" alt="wut" src="https://user-images.githubusercontent.com/7811733/216837311-76d1a80a-7caf-4b1e-8b24-9fd1b2400b2d.png">

Seeing this warning as of today for no obvious reasons. I've implemented the [requirements](https://shopify.dev/apps/tools/app-bridge/updating-overview#ensure-compatibility-with-the-new-shopify-admin-domain) as @AaronSpringut mentioned above more than a month ago.

I'm returning my app's HTML file in under 200ms, CSP headers are set. App bridge is loaded immediately. Any pointers?

**Comment by muraliavarma** [comment]
I have the same exact problem as above commenter, even after upgrading to app bridge v3, adding in the new CSP entry. Interesting thing is that my local version that runs on `ngrok` works fine while my production build is throwing this error. Totally confused about this.

**Comment by kragotte** [comment]
Hi all,

This banner should now be checking to see if your app has ever loaded successfully in the new admin domain (admin.shopify.com), and will not redirect the merchant if it ever has loaded successfully. Testing apps through partner dev stores (all of which should now be on the new admin domain) is the fastest path to us recording a successful load. Make sure your app is loading beneath the banner displayed on admin.shopify.com.

Our data pipeline is updated approximately every 3hrs. Since your comments were about 5-6hrs ago, you should not be seeing the banner any more. If you are seeing your app load on admin.shopify.com, but are still seeing the banner and getting redirected, please reach out to partner support so that we can dig into your specific situation further.

**Comment by muraliavarma** [comment]
This partially works. The warning went away for one of the stores that had the app installed. But new stores that are installing this app is still showing the banner

**Comment by avtans-kumar-shipsy** [comment]
@kragotte @AaronSpringut I have created a new app which uses App Bridge 3 (`"@shopify/app-bridge": "^3.1.0"`) out of the box, for which it was mentioned that the apps created by Shopify CLI 3.x is already setup to handle the unified admin domain changes (https://shopify.dev/apps/tools/app-bridge/getting-started/app-setup). But even after that, on successful installs of my app on any development test store, 2 tabs open up - one with `admin.shopify.com` and the other with `storename.myshopify.com` with `force_legacy_domain=1` as query params.

The banners showed up initially and as per the [response](https://github.com/Shopify/shopify-app-bridge/issues/160#issuecomment-1418313133), it seems that the banner is no longer showing up, but I'm still getting redirected. Any idea what is going wrong here?

**Comment by dani-sanomads** [comment]
I'm facing the same issue mentioned by @avtans-kumar-shipsy . Any Updates? @kragotte  @AaronSpringut

**Comment by rosantoz** [comment]
@Mark-H In my case yes, they do. However the problem persists for new installs. 

@kragotte confirmed there's an issue (in the reply above):

>  we have identified a bug related to showing the banner on new installs of recently updated apps

**Comment by avibz1987** [comment]
any news about this?

**Comment by meltinbit** [comment]
same for me, my app approval was rejected cause of this issue

**Comment by blazeorion** [comment]
@mithatb this is still a problem for me

**Comment by huynq2007** [comment]
@kragotte Same issues here. 
We have been submitting our app but it got rejected due to the banner issue. We have confirmed that the App bridge version and CSP are correctly configured already. 
After trying to resubmit our app, we have not received any feedback from the review team yet. 
I guess we need to wait for a more few days

**Comment by qq99** [comment]
![image](https://user-images.githubusercontent.com/150352/220721026-426e834d-dd35-41ba-8a6d-a9e7eb6d6b9f.png)
Seeing this for the first time today when going to re-submit app for review

![image](https://user-images.githubusercontent.com/150352/220721169-f7ce31c0-8ce1-41ac-baa7-1427dd296a10.png)

I started wondering if perhaps it's due to the ordering of the hosts in the CSP directive?

**Comment by rosantoz** [comment]
For everyone stuck at the review process because of this:

The way I solved was by sending a support request via the partner portal asking them to opt out the app from this feature.

Here's the response from the Partner Support:

```
I just wanted to update you that our current work around for this issue is to add beta feature to remove this banner. I would like to share with you that I have added this feature and this issue should be resolved for now.
```

Unfortunately we are forced to use App Bridge for embedded apps, but when things go wrong on Shopify's side there not communication or support. Partners are left to figure out things by themselves.

This issue as reported 106 days ago and there's still no resolution. I'm sure a company with a $58b market cap can afford a developer or a small team to take care of things like this. It's really disappointing how this has been handled so far.

I hope this helps whoever is stuck in the review process because of this.

**Comment by webrexRavi** [comment]
@kragotte still happening in my app, need your help on this 

Is anyone else found the solution ?

**Comment by webrexRavi** [comment]
Now it is working for me(Resolved automatically), day before yesterday it wasn't.

I think it may take some time to get resolved from shopify's end (their data pipeline can take upto 3 hours to update) - https://github.com/Shopify/shopify-app-bridge/issues/160#issuecomment-1430527337

**Comment by PaulvdDool** [comment]
My app is still opening in a new app as soon as I click the link to open it.
The new tab is already triggered before a my app is properly loaded (checked by adding a console.log to the pages/_app.tsx file in my NextJS project).

I no longer get the banner that says the app loads too slow, but the opening in new tab is still there.

The correct Content-Security-Policy is added to all my requests.
I'm using App Bridge through the `@shopify/app-bridge` package that is on version 3.7.4.
So in that sense I meet all conditions.

Since this issue has been mostly dormant for the last month I'm wondering if I'm alone on this issue.

**Comment by PhiloNL** [comment]
@kragotte I'm still having this issue. I also don't quite understand why this occurs for only some of my apps (while they use the same base framework). Any update on how to resolve this?

**Comment by kj** [comment]
I'm also experiencing this as of about a week ago, even though I am pretty sure I have the CSP's frame-ancestors set up properly and am on the newest version of App Bridge. It also only occurs on my dev app, not my production app, although my dev app is undergoing a major rewrite.

**Comment by kj** [comment]
Strangely it's suddenly working for me today, with no legacy domain popup. I didn't change anything (today specifically), and I have had the popup consistently for the last month, so I'm not sure if Shopify fixed something on their end, or marked my app in some way (as I've been in contact with support). They haven't said anything at least, but I'll update if it starts happening again. I was on 3.7.6 when I noticed the popup was gone, so I just updated to 3.7.7 and still okay.

**Comment by prashant-chai** [comment]
It is happening to us.

Two tabs open and one of the tabs with force_legacy_domain=1, the app loads in both.
Received an email from the Shopify team about sending Content-Security-Policy: frame-ancestors in response headers but the app does it 

```
app.use((req, res, next) => {
    const shop = req.query.shop;
    if (Shopify.Context.IS_EMBEDDED_APP && shop) {
      res.setHeader(
        "Content-Security-Policy",
        `frame-ancestors https://${shop} https://admin.shopify.com;`
      );
    } else {
      res.setHeader("Content-Security-Policy", `frame-ancestors 'none';`);
    }
    next();
  });
```

**Comment by phongdh-lftv** [comment]
For embedded apps to work correctly on the new admin domain, ensure:
I. The [content security policy](https://shopify.dev/apps/store/security/iframe-protection) includes admin.shopify.com.
II. The app is on [App Bridge 2.0 or higher](https://shopify.dev/apps/tools/app-bridge/migrating-to-2). We recommend upgrading to [App Bridge 3.0](https://shopify.dev/apps/tools/app-bridge/migrating-to-3).
III. The app has correctly implemented the[ host parameter](https://shopify.dev/apps/tools/app-bridge/retrieve-the-host).

**I) Set The Content Security Policy**
```
const shop = req.query.shop;
res.setHeader(
      "Content-Security-Policy",
      `default-src https: 'self'; script-src https: 'unsafe-inline' 'unsafe-eval' 'self' unpkg.com cdn.shopify.com cdn.shopifycloud.com; style-src https: 'unsafe-inline' cdn.shopifycloud.com; img-src 'self' https: data: cdn.shopifycloud.com blob:; upgrade-insecure-requests; frame-ancestors https://${shop} https://admin.shopify.com;`
    );
```

**II) By way use App Bridge 3.0, in your embedded app**
```
<script src="https://unpkg.com/@shopify/app-bridge@3"></script>
<script>
    const AppBridge = window['app-bridge'];
    const appBridge = AppBridge.createApp({
        apiKey: '<Client ID in your app>',
        host: new URLSearchParams(location.search).get("host"),
        forceRedirect: true
    });
</script>
```

**III) Use `host parameter`**
As you see in II) `host: new URLSearchParams(location.search).get("host"),`. **_Please keep this. DO NOT CHANGE_**



## OPTIONAL
If you want to use [`session token authentication`](https://shopify.dev/docs/apps/auth/oauth/session-tokens/getting-started) so then

**1. Get session token**
```
AppBridge.utilities.getSessionToken(appBridge).then(function(sesionToken) {
    console.log(sesionToken);
});
```

**2. Using session token**
```
$.ajax({
    .
    .
    "headers": {
        "Authorization": `Bearer ${sessionToken}`,
    }
    .
    .
});
```

**3. Verify session token with `Client secret` in your app. Use package: jsonwebtoken** (https://www.npmjs.com/package/jsonwebtoken)
```
'use strict';
const jwt = require('jsonwebtoken');

const verifyToken = (token) => {
  return new Promise((resolve, reject) => {
    jwt.verify(token, 'Client secret in your app', (error, decoded) => {
      if (error) {
        return reject(error);
      }

      resolve(decoded);
    });
  });
};

const data = verifyToken('your session token from request.headers.authorization')
```

**Comment by prashant-chai** [comment]
Hi @thesunilyadav , the key is not to add the app URL as your backend, it should hit the frontend app and then you can do your processing or forward the the request to backend

**Comment by thesunilyadav** [comment]
> Hi @thesunilyadav , the key is not to add the app URL as your backend, it should hit the frontend app and then you can do your processing or forward the the request to backend

We have a Laravel app that combines both the front-end and backend. Therefore, the host or App URL is identical for both the front-end and backend

**Comment by lexcao** [comment]
Hi @charlesdobson 
We have met the same issue, could you please try enabling the flag for our App **(ID: 6155457)**
- using the 3.0+ version of AppBridge with React
- including the Content-Security-Policy header

**Comment by charlesdobson** [comment]
@lexcao Done. Please try it out again :)

**Comment by lexcao** [comment]
Hi @charlesdobson 
It works! Thank you, you are awesome!

**Comment by geoffrey-syncx** [comment]
Hi @charlesdobson 
My company app StockSync (id: 198941) just turn on the embed option, having the same issue which is open a new tab when clicked in shopify admin. Can you help look into that?

Another question I want to ask, is the requirment App Bridge ver 3 is able to fulfil by using CDN version of app bridge (https://shopify.dev/docs/api/app-bridge-library)?

**Comment by agafonec** [comment]
Hi @charlesdobson , i'm facing same issue after moving from standalone app to embedded app that it's opening 1 extra tab with some url parameter `force_legacy_domain=1`.  i'm using laravel and vue for the app with latest app bridge version, and also including the Content-Security-Policy header. this is my App ID: 22693412865 (hopefully it's correct one i took it from url). if you can help me with that it would be great. thanks

**Comment by huynhmaianhkiet** [comment]
I have encountered an issue after transitioning from a standalone app to an embedded app. Although our app is still functioning properly, I have received a warning stating "This app is taking a while to load". Even when I tried to make my dashboard app empty (without any code), the warning continued to appear.

![Screenshot 2024-05-19 at 15 30 53](https://github.com/Shopify/shopify-app-bridge/assets/9443713/0ce98355-e0ad-44aa-b465-8749481ae963)

However, I found that if I add the parameter "?force_legacy_domain=1" when loading the app, the warning does not appear.

I am currently using the app with the latest App Bridge version and have also included the Content-Security-Policy header.

I would greatly appreciate your assistance with this matter.

Thank you

**Comment by charlesdobson** [comment]
@huynhmaianhkiet what's your app ID?

**Comment by huynhmaianhkiet** [comment]
> @huynhmaianhkiet what's your app ID?
Hi @charlesdobson, my app ID is 14667415553. Can help me enable a beta flag for it, please?

Best regards,

**Comment by mfyz** [comment]
> ...we're noticing that there's a significant delay from when someone clicks on our app and when Shopify calls our App URL. The timing that we are seeing often is: User clicks on our app, ~3 seconds later Shopify calls our App URL, our App returns in ~300ms. We are concerned about how this appears to users since from what we can control, our app takes on average 300ms. We believe the extra loading time is reflecting badly on our load speeds. It appears that this does not happen with other apps and they are loaded in in 1s or less.

My app is having exact same behavior. Shopify takes about 2-3 seconds before the iframe hits my app and my app renders in 300ish ms. And the page loads and all, then in 1-2 seconds later, I get the "This app is taking a while to load." banner which is weird because the app is loaded, there is no web vitals activity (like LCP, and all is already resolved in the "performance profiler").

Is this a meta flag that my app got flagged when it was running on older version of app-bridge-react, and now I upgraded, will it take some time to shopify to detect the speed improvement, and reverse the flag? Is that what you were doing manually @charlesdobson ? I definitely see, doing this manually is not the way, and I'm ok to wait it out, but if it will not go away by itself, then I need to understand what's the next steps...

**Comment by djhayman** [comment]
Please disregard, someone at Shopify Partner Support was able to resolve the issue

**Comment by henrytao-me** [comment]
@itsmekhmtz can you leave your appId here?

**Comment by geoffrey-syncx** [comment]
Hi @henrytao-me here is my app 
1270200 Production App 

I am try to make my production app (1270200) embed, when i test on test app (66919104513), it works ok, but when on production app (1270200), it show an error `APP::ERROR::INVALID_CONFIG: host must be provided`



![Image](https://github.com/user-attachments/assets/d60d6331-3fde-4f39-9e0a-e8ac04935710)

I found that this error is come from app bridge ver 2

but i am using app bridge ver cdn

**Comment by geoffrey-syncx** [comment]
Hi @henrytao-me ,

syncX Order Export id:1270200 

It show the outdated warning banner, but i am using cdn ver app bridge

Can you help me to remove, since it confuse our users

![Image](https://github.com/user-attachments/assets/3e7f13b2-859f-4cc0-8309-c9ea97a9652e)

![Image](https://github.com/user-attachments/assets/492df6aa-cd7b-42b2-85ec-924b5f9e5fb7)

**Comment by huynhmaianhkiet** [comment]
You might be using an outdated version of Rest API or GraphQL. Please verify and, if necessary, update to the most recent version.
