### ISSUE TITLE
`ui-modal` is showing a loading spinner for static content

### ISSUE THREAD

**Issue by darrynten** [Shopify/shopify-app-bridge#314]
## Describe the bug

The `ui-modal` is showing a loading spinner for static contents (i.e. when not using the `src` attribute)

### To Reproduce

Steps to reproduce the behaviour:

1. Add a `ui-modal` component to an app with just a single `<p>` tag and a `ui-title-bar` component
2. Call `.show()` on the modal
3. See a loading spinner before the contents of the `<p>` tag is rendered

```html
<ui-modal id="example-modal">
  <p>This content should be rendered immediately, without any loading spinners.</p>
  <ui-title-bar title="Example Static Modal">
    <button variant="primary" onclick="console.log('primary')">Action A</button>
    <button onclick="console.log('secondary')">Action B</button>
  </ui-title-bar>
</ui-modal>
```

```js
document.getElementById('example-modal').show()
```

<img width="469" alt="image" src="https://github.com/Shopify/shopify-app-bridge/assets/3657251/ef152d5c-15f5-4747-b09d-c54bf39ecbbc">

### Expected behaviour

A loading spinner should only ever be shown if the `src` attribute is used when loading remote content as static content is already available when the `show()` method is called.

Static content should be rendered immediately like it is with the `Modal` action from v3.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `cdn`

## Platform

- OS: All
- OS Version: All
- App: All

### Additional context

Adding a `variant` to the modal does not make a difference

**Comment by jzazove** [comment]
We are looking into this

**Comment by GoodJavaJobs** [comment]
Hi @jzazove , Facing the same issue as well.  My modal basically full of static content but I still see a spinner for for the first 5 seconds.

**Comment by fabregas4** [comment]
The modal provides such a poor user experience. You have to wait a few seconds for the modal to open basic, already available content, when no src attribute is passed. Not sure how this isn't getting a higher priority?

**Comment by nullndr** [comment]
Any news on this?

**Comment by fabregas4** [comment]
Noticed another issue with this, kind of related.

Font-sizes within the modal are huge when using Polaris components. That's because it's using the same breakpoints as the embedded app page, and the modal is small.

It is effectively treating the modal iframe as mobile device size, and applying the large text that Polaris does for mobile, which doesn't match the font-size of the content behind the modal at all, when on desktop. 

Not easy to override either as Polaris components use rem sizing which refer back to the size at the HTML document level.

**Comment by steveroseik** [comment]
Same issue, any updates?

**Comment by fabregas4** [comment]
@steveroseik I think that's the right answer for the moment unfortunately, despite the Polaris Modal being deprecated. I just implemented it and it works really nice. Hopefully the team get the app bridge Modal working a lot better soon. At least they say they are working on it (https://github.com/Shopify/polaris/issues/11460).

**Comment by iwoodruff** [comment]
> I've started getting the following message when opening modals that contain only static content:
> 
> ```
> The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
> ```
> 
> and
> 
> ```
> app-bridge.js:1 The modal src is missing App Bridge CDN script tag.
> ```
> 
> The time it takes to open a modal containing a single `<p>` tag is now also somehow longer than when I first opened this issue.

Hey @darrynten – thank you for your attention to modals & for raising the issues to us – we are actively working on your feedback (along with others) & appreciate all the details you've provided

Looking at the above post, there are a few things to address:
- I'm not sure the root cause of the preloading warning & need to follow up with my team
- for the missing App Bridge CDN script warning, that's intentional since app bridge modals render in a separate iframe from the embedded app home (which allows it to be centered over the Shopify Admin & inherit the latest styles vs centered within the app iframe & pinned to a version of Polaris). since there are two separate (but same origin) window contexts, we want app bridge in both of those contexts so the two can communicate with each other

**Comment by darrynten** [comment]
Any updates on this?

**Comment by anikmoz** [comment]
Any update on this ?

**Comment by jzazove** [comment]
There is no longer spinners in the modals.  
We also published a page with guidance on when/how to use modals: https://shopify.dev/docs/api/app-bridge/using-modals-in-your-app

**Comment by kirillplatonov** [comment]
@jzazove This is really great. Thank you for these improvements!

**Comment by fabregas4** [comment]
@jzazove Thanks! Seems to be working well.

The only thing I'm noticing as lacking vs the Polaris Modal, now that I've switched it over, is the ability to set loading state on the buttons.

On the Polaris Modal, you could do the below and the primary button would display a loading spinner while you're submitting and checking for server-side errors.
```primaryAction={{
	content: "Save",
	onAction: handleSaveOrderSubmit,
	loading: saveOrder.state !== 'idle'
}}```

The doesn't seem to be an equivalent way to do this using the TitleBar buttons within the app bridge Modal. If there's an easy solution please let me know, otherwise I can raise as a separate issue.

**Comment by benjitastic** [comment]
I was still getting this issue with `"@shopify/app-bridge-react": "^4.2.1",` loading static content in a ui-modal for the 1st time.

Switched back to deprecated `{ Modal } from "@shopify/polaris";`

**Comment by wcHarsh** [comment]
Hello @jzazove one typo found in this doc :- https://shopify.dev/docs/api/app-bridge/using-modals-in-your-app

Reference link :- https://prnt.sc/UP2h08aw7VPV

<img width="1912" height="995" alt="Image" src="https://github.com/user-attachments/assets/78df73d2-60c1-4a4e-95fd-9e5f3ffb84ff" [/>``](url)

**Comment by kirillplatonov** [comment]
Recently Shopify released new modals as part of new Polaris web components. They're much better fit for simple modals with static content. I recorded video with comparison: https://youtu.be/xtMTFHYUOgk
