### ISSUE TITLE
Resource Picker with Typescript - expose types

### ISSUE THREAD

**Issue by Alagaesia93** [Shopify/shopify-app-bridge#354]
### Describe the feature you’d like

```javascript
const [shopifyVariants, setShopifyVariants] = useState<ProductVariant[]>([])
const handleSelect = async (query: string) => {
  const selected = await shopify.resourcePicker({ type: 'product', multiple: true, query: query })
  if (selected && selected.length > 0) setShopifyVariants(selected.map((product: Product) => product.variants))
}
```
There is no exposed ProductVariant and Product types, so I'm forced to use `any`
I'm no Javascript / React expert, maybe there is another solution I did not consider

### Describe alternatives you've considered

`const [shopifyVariants, setShopifyVariants] = useState<any[]>([])`
but that kind of misses the point of Typescript :)

**Comment by thuan1412** [comment]
it's a error with @shopify/app-bridge-types@0.0.15. Downgrade to 0.0.11 should fix the issue. I have to modify my yarn.lock file to tell VsCode to look at @shopify/app-bridge-types@0.0.11 for correct type narrow.

**Comment by thuan1412** [comment]
How about other types as well? For example, I can't get type of `BaseResource`, so I have to re-write that type in my project.

**Comment by nozzlegear** [comment]
This is still an issue. The workarounds mentioned above work, but the people crave a new release. They yearn for it!

**Comment by nboliver-ventureweb** [comment]
Also a problem for me, please fix.

**Comment by antoineskt** [comment]
I have the same problem

**Comment by SerhiiGoTolstoy** [comment]
Same issue here, please export types 🙏

**Comment by ozzyonfire** [comment]
Just an FYI for people. Here is how I fixed this in my project.

1. use pnpm as your package manager.
2. pnpm patch @shopify/app-bridge-types
3. open project and navigate to the dist/shopify.ts file.
4. locate the types you want (i.e. Collection, Product, ProductVariant - anything that extends Resource).
5. put the export keyword infront of these interfaces.
6. Go to index.d.ts and export them from this file as well. 

ie. the new `index.d.ts` file looks like this
```ts
import type {
  ShopifyGlobal,
  AugmentedElement,
  AppBridgeElements,
  AppBridgeAttributes,
  UIModalElement as BaseUIModalElement,
  UINavMenuElement as BaseUINavMenuElement,
  UITitleBarElement as BaseUITitleBarElement,
  UISaveBarElement as BaseUISaveBarElement,
  UIModalAttributes,
  UINavMenuAttributes,
  UITitleBarAttributes,
  UISaveBarAttributes,
  ResourceTypes,
  Product,
  ProductVariant,
  Collection,
} from "./shopify";

export {
  ShopifyGlobal,
  UIModalAttributes,
  UINavMenuAttributes,
  UITitleBarAttributes,
  UISaveBarAttributes,
  ResourceTypes,
  Product,
  ProductVariant,
  Collection,
};

declare global {
  var shopify: ShopifyGlobal;

  // Install property augmentations onto DOM prototypes
  interface HTMLButtonElement extends AugmentedElement<"button"> {}
  interface HTMLAnchorElement extends AugmentedElement<"a"> {}

  interface UIModalElement extends BaseUIModalElement {}
  interface UINavMenuElement extends BaseUINavMenuElement {}
  interface UITitleBarElement extends BaseUITitleBarElement {}
  interface UISaveBarElement extends BaseUISaveBarElement {}

  // Install property augmentations onto ReactElement prop definitions
  namespace React {
    interface ButtonHTMLAttributes<T> extends AugmentedElement<"button"> {}
    interface AnchorHTMLAttributes<T> extends AugmentedElement<"a"> {}
  }

  // Install Element/attribute augmentations into JSX definitions
  namespace JSX {
    interface IntrinsicElements extends AppBridgeElements {}
    interface IntrinsicAttributes extends AppBridgeAttributes {}
  }
}
```

Now you can use these types acroos your app by just importing them from @shopify/app-bridge-types.

**Comment by sameerxanand** [comment]
Alternatively, `"@shopify/app-bridge-core/actions/ResourcePicker";` exports the types 🙂

But agree with everyone else in this thread... Please export the types 🙏. I spent way to many hours last night trying to wrap my head around this.

Also, the implementation of the return type is terrible. The documentation [here](https://shopify.dev/docs/api/app-bridge-library/apis/resource-picker#resource%20picker%20return%20payload) says that "the object type in the array varies based on the provided type option." The implementation should return the correct type or undefined based on the `type` provided. For example, this code:

```ts
import { BaseResource } from "@shopify/app-bridge-core/actions/ResourcePicker";
import { useAppBridge } from "@shopify/app-bridge-react";
import { ResourcePicker } from "@shopify/app-bridge/actions";

export default function useResourcePicker() {
  const app = useAppBridge();

  async function open(
    initialSelections: BaseResource[],
    callback: (selections: BaseResource[]) => void | Promise<void>,
  ) {

    // ‼️ selections is typed as  SelectPayload<"product" | "variant" | "collection"> | undefined
    const selections = await app.resourcePicker({
      type: ResourcePicker.ResourceType.Product,
      multiple: true,
      action: "select",
      filter: {
        variants: true,
        draft: false,
        query: "bundles:false",
        archived: false,
        hidden: false,
      },
      selectionIds: initialSelections,
    });

    // Case when user cancels or clicks outside the picker, triggering it to close.
    if (selections === undefined) return;

    // Call the callback function with the user's selections.
    await callback(selections);
  }

  return { open };
}
```

The `selections` variable is getting typed as `SelectPayload<"product" | "variant" | "collection"> | undefined`. Because of this, its difficult to do anything with `selections` because you only see the common properties among the three types. In my example, I'd expect `selections` to be typed as `Product[] | undefined` because my type is set to `ResourcePicker.ResourceType.Product` and `multiple` as true.

**Comment by seaders** [comment]
> This is a bit frustrating. The shopify.resourcePicker could at least have been generic.
> 
> The best way forward I found was to use some of the utility types TypeScript offers to manually extract the union:
> 
> type PickerUnion = NonNullable<Awaited<ReturnType<typeof shopify.resourcePicker>>>[number];
> 
> // These were the best discriminators I found.
> type Product = Extract<PickerUnion, { productType: any }>;
> type ProductVariant = Extract<PickerUnion, { product: any }>;
> type Collection = Extract<PickerUnion, { productsCount: any }>;
> 
> It's definitely possible to use some more typescript type magic to make it more usable. Here's how far I got before deciding to go with my solution above:
> 
> type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
>     k: infer I
>   ) => void
>   ? I
>   : never;
> type PopUnion<U> = UnionToIntersection<U extends any ? (u: U) => void : never> extends (u: infer A) => void
>   ? A
>   : never;
> type UnionToArray<U, A extends unknown[] = []> = [U] extends [never]
>   ? A
>   : UnionToArray<Exclude<U, PopUnion<U>>, [PopUnion<U>, ...A]>;
> 
> type PickerUnion = NonNullable<Awaited<ReturnType<typeof shopify.resourcePicker>>>[number];
> type TypesAsArray = UnionToArray<PickerUnion>;
> 
> type Product = TypesAsArray[0];
> type ProductVariant = TypesAsArray[1];
> type Collection = TypesAsArray[2];

I've used this message until today when I've just learned another (and in my opinion better and cleaner) way,

`
type PickerTypes = NonNullable<
  Awaited<ReturnType<typeof shopify.resourcePicker>>
>[number]

export type ResourceProduct = Extract<PickerTypes, { productType: string }>

export type ResourceProducts = ResourceProduct[] | undefined

export type ResourceVariants =
  | Extract<PickerTypes, { product: Partial<ResourceProduct> }>[]
  | undefined

export type ResourceCollections =
  | Extract<PickerTypes, { productsCount: number }>[]
  | undefined
`

I had an issue where, when developing, the order of `TypesAsArray` would get mixed up, and I would get errors in my code where it would think a Collection response was Products, or Products was Variants, or something.  This way prevents that.

**Comment by daviareias** [comment]
> it's a error with @shopify/app-bridge-types@0.0.15. Downgrade to 0.0.11 should fix the issue. I have to modify my yarn.lock file to tell VsCode to look at @shopify/app-bridge-types@0.0.11 for correct type narrow.

It seems we're currently in version 0.2.0 and they did not fix this.
